db:
 image: postgres

test:
  build: .
  command: python manage.py behave
  volumes:
    - .:/code
 depends_on:
   - db

deploy:
  script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl
  - dpl --provider=heroku --app=betsmania --api-key=$HEROKU_STAGING_API_KEY
  only:
    - master
